Build/storybook
site-bender/html-patterns-spec pull request #1
Opened 2022-01-05 22:27 UTC by natebowang

Setup the Storybook.

2022-01-05 22:31 UTC, natebowang commented on atoms/button/index.ts
> +export type Props = {
We use 'ButtonProps' as the props type's name in The Jac. I change it to 'Props' to avoid renaming the prop when renaming the component. Not sure if this is good.

2022-01-05 22:33 UTC, natebowang commented on atoms/button/index.ts
> +export default function button({disabled, text}: Props) {
Should the component name be PascalCase?

2022-01-06 00:02 UTC, chasm commented on atoms/button/index.ts
> +export default function button({disabled, text}: Props) {
If it's our component, then yes, I think so. Otherwise, how to distinguish?

2022-01-06 00:02 UTC, chasm commented on atoms/button/index.ts
> +export type Props = {
OK for now. We'll look at it.

2022-01-06 00:04 UTC, chasm requested changes

2022-01-06 00:04 UTC, chasm commented on atoms/button/index.story.ts
> +Primary.args = {
Can we put a blank line here? Putting the `Primary.args` line immediately below the export makes it difficult to read.

2022-01-06 00:44 UTC, chasm approved these changes
Nice.

2022-01-06 00:44 UTC, merged